"""Pydantic models for the LLM-backed pipeline.

All models use Pydantic v2 for strict validation.
Each model corresponds to a structured output step in the pipeline.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


# ── Candidate Extraction ──────────────────────────────────────────────

class CandidateMemory(BaseModel):
    """A single memory candidate extracted from a conversation transcript."""
    content: str = Field(
        ...,
        description="The extracted memory content (fact, decision, or observation).",
        max_length=2000,
    )
    memory_type: str = Field(
        default="episodic",
        description="Type of memory: episodic, semantic, procedural, or decision.",
    )
    room: str = Field(
        default="general",
        description="Target room for this memory (e.g. decisions, config, general).",
    )
    importance: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Estimated importance score 0.0–1.0.",
    )
    entities: list[str] = Field(
        default_factory=list,
        description="Key entities mentioned (people, projects, tools, concepts).",
    )
    temporal_context: str | None = Field(
        default=None,
        description="Temporal qualifier if present (e.g. 'by Q3', 'starting next week').",
    )


class ExtractionResult(BaseModel):
    """Structured result of the candidate extraction step."""
    candidates: list[CandidateMemory] = Field(
        ...,
        description="Extracted memory candidates.",
    )
    summary: str | None = Field(
        default=None,
        description="Optional one-sentence summary of the conversation.",
    )


# ── Review & Score ────────────────────────────────────────────────────

class ReviewVerdict(BaseModel):
    """Verdict from reviewing a single memory candidate."""
    action: str = Field(
        ...,
        description="Decision: promote, drop, or revise.",
        pattern=r"^(promote|drop|revise)$",
    )
    revised_content: str | None = Field(
        default=None,
        description="Revised content if action is 'revise'.",
        max_length=2000,
    )
    importance_score: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="LLM-assigned importance score.",
    )
    reasoning: str | None = Field(
        default=None,
        description="Brief justification for the verdict.",
        max_length=500,
    )
    contradictions: list[str] = Field(
        default_factory=list,
        description="IDs or content snippets this memory contradicts.",
    )
    suggested_room: str = Field(
        default="general",
        description="Best room classification for this memory.",
    )
    entities: list[str] = Field(
        default_factory=list,
        description="Entities identified during review.",
    )


class ReviewBatchResult(BaseModel):
    """Result of reviewing a batch of candidates."""
    verdicts: list[ReviewVerdict] = Field(
        ...,
        description="One verdict per candidate in order.",
    )


# ── Consolidation ─────────────────────────────────────────────────────

class MergeGroup(BaseModel):
    """A group of memories that should be merged."""
    keep_id: str = Field(..., description="ID of the memory to keep.")
    merge_ids: list[str] = Field(
        ...,
        description="IDs of memories to merge into the kept one.",
        min_length=1,
    )
    merged_content: str = Field(
        ...,
        description="Consolidated content after merging.",
        max_length=2000,
    )
    reason: str = Field(
        ...,
        description="Why these should be merged (semantic similarity / contradiction).",
    )


class ConsolidationPlan(BaseModel):
    """Plan for consolidating a set of memories."""
    merges: list[MergeGroup] = Field(
        default_factory=list,
        description="Groups of memories to merge.",
    )
    stalls: list[str] = Field(
        default_factory=list,
        description="IDs of memories to mark as stale/superseded.",
    )
    reason: str | None = Field(
        default=None,
        description="Overall analysis summary.",
    )


# ── Daily Summary ─────────────────────────────────────────────────────

class DailySummary(BaseModel):
    """Structured daily summary generated by the LLM."""
    date: str = Field(
        ...,
        description="Date string in YYYY-MM-DD format.",
    )
    total_memories: int = Field(
        ...,
        description="Total number of memories created today.",
    )
    by_room: dict[str, int] = Field(
        default_factory=dict,
        description="Count of memories per room.",
    )
    key_decisions: list[str] = Field(
        default_factory=list,
        description="Critical decisions made today.",
        max_length=10,
    )
    key_observations: list[str] = Field(
        default_factory=list,
        description="Important observations or facts.",
        max_length=10,
    )
    action_items: list[str] = Field(
        default_factory=list,
        description="Action items extracted from today.",
        max_length=5,
    )
    conflicts_resolved: int = Field(
        default=0,
        description="Number of conflicts detected and resolved.",
    )
    narrative: str | None = Field(
        default=None,
        description="Optional one-paragraph narrative summary.",
        max_length=1000,
    )


# ── Evolution Report ──────────────────────────────────────────────────

class EvolutionStep(BaseModel):
    """A single step in the evolution report."""
    step: str = Field(..., description="Name of the evolution step.")
    status: str = Field(
        ...,
        description="Status: success, skipped, warning, or error.",
    )
    details: dict[str, Any] = Field(
        default_factory=dict,
        description="Step-specific details.",
    )


class EvolutionReport(BaseModel):
    """Complete structured report from an evolution cycle."""
    steps: list[EvolutionStep] = Field(
        ...,
        description="Ordered list of evolution steps executed.",
    )
    promoted: int = Field(0, description="Number of memories promoted.")
    merged: int = Field(0, description="Number of memories merged.")
    dropped: int = Field(0, description="Number of memories dropped.")
    errors: list[str] = Field(
        default_factory=list,
        description="Any errors encountered during evolution.",
    )
    duration_ms: int = Field(0, description="Total duration in milliseconds.")
    llm_used: bool = Field(False, description="Whether LLM was used in this cycle.")
